export const data = [
  {
    id: 0,
    company: 'Photosnap',
    position: 'senior frontend developer',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi fuga alias quidem temporibus, sed, illum molestiae nostrum, in accusamus unde repellendus perspiciatis. Voluptate ducimus sunt nam laudantium id cum inventore!',
    date: '2023-01-26',
    type: 'full time',
    location: 'USA only',
    isFeatured: true,
    tags: ['frontend', 'senior', 'html', 'css', 'javascript'],
  },
  {
    id: 1,
    company: 'MyHome',
    position: 'junior frontend developer',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi fuga alias quidem temporibus, sed, illum molestiae nostrum, in accusamus unde repellendus perspiciatis. Voluptate ducimus sunt nam laudantium id cum inventore!',
    date: '2023-01-25',
    type: 'contract',
    location: 'USA only',
    isFeatured: false,
    tags: ['frontend', 'junior', 'css', 'javascript'],
  },
  {
    id: 2,
    company: 'Manage',
    position: 'fullstack developer',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi fuga alias quidem temporibus, sed, illum molestiae nostrum, in accusamus unde repellendus perspiciatis. Voluptate ducimus sunt nam laudantium id cum inventore!',
    date: '2023-01-20',
    type: 'part time',
    location: 'remote',
    isFeatured: true,
    tags: ['fullstack', 'middle', 'python', 'react'],
  },
  {
    id: 3,
    company: 'Loop Studios',
    position: 'software engineer',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi fuga alias quidem temporibus, sed, illum molestiae nostrum, in accusamus unde repellendus perspiciatis. Voluptate ducimus sunt nam laudantium id cum inventore!',
    date: '2023-01-17',
    type: 'full time',
    location: 'worldwide',
    isFeatured: false,
    tags: ['fullstack', 'middle', 'sass', 'javascript', 'ruby'],
  },
  {
    id: 4,
    company: 'FaceIt',
    position: 'backend developer',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi fuga alias quidem temporibus, sed, illum molestiae nostrum, in accusamus unde repellendus perspiciatis. Voluptate ducimus sunt nam laudantium id cum inventore!',
    date: '2023-01-06',
    type: 'full time',
    location: 'UK only',
    isFeatured: false,
    tags: ['backend', 'junior', 'ruby', 'ror'],
  },
  {
    id: 5,
    company: 'Photosnap',
    position: 'senior frontend developer',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi fuga alias quidem temporibus, sed, illum molestiae nostrum, in accusamus unde repellendus perspiciatis. Voluptate ducimus sunt nam laudantium id cum inventore!',
    date: '2023-01-26',
    type: 'full time',
    location: 'USA only',
    isFeatured: false,
    tags: ['frontend', 'senior', 'html', 'css', 'javascript'],
  },
  {
    id: 6,
    company: 'MyHome',
    position: 'junior frontend developer',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi fuga alias quidem temporibus, sed, illum molestiae nostrum, in accusamus unde repellendus perspiciatis. Voluptate ducimus sunt nam laudantium id cum inventore!',
    date: '2023-01-25',
    type: 'contract',
    location: 'USA only',
    isFeatured: false,
    tags: ['frontend', 'junior', 'css', 'javascript'],
  },
  {
    id: 7,
    company: 'Manage',
    position: 'fullstack developer',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi fuga alias quidem temporibus, sed, illum molestiae nostrum, in accusamus unde repellendus perspiciatis. Voluptate ducimus sunt nam laudantium id cum inventore!',
    date: '2023-01-20',
    type: 'part time',
    location: 'remote',
    isFeatured: false,
    tags: ['fullstack', 'middle', 'python', 'react'],
  },
  {
    id: 8,
    company: 'Loop Studios',
    position: 'software engineer',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi fuga alias quidem temporibus, sed, illum molestiae nostrum, in accusamus unde repellendus perspiciatis. Voluptate ducimus sunt nam laudantium id cum inventore!',
    date: '2023-01-17',
    type: 'full time',
    location: 'worldwide',
    isFeatured: false,
    tags: ['fullstack', 'middle', 'sass', 'javascript', 'ruby'],
  },
  {
    id: 9,
    company: 'FaceIt',
    position: 'backend developer',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi fuga alias quidem temporibus, sed, illum molestiae nostrum, in accusamus unde repellendus perspiciatis. Voluptate ducimus sunt nam laudantium id cum inventore!',
    date: '2023-01-06',
    type: 'full time',
    location: 'UK only',
    isFeatured: false,
    tags: ['backend', 'junior', 'ruby', 'ror'],
  },
  {
    id: 10,
    company: 'Photosnap',
    position: 'senior frontend developer',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi fuga alias quidem temporibus, sed, illum molestiae nostrum, in accusamus unde repellendus perspiciatis. Voluptate ducimus sunt nam laudantium id cum inventore!',
    date: '2023-01-26',
    type: 'full time',
    location: 'USA only',
    isFeatured: false,
    tags: ['frontend', 'senior', 'html', 'css', 'javascript'],
  },
  {
    id: 11,
    company: 'MyHome',
    position: 'junior frontend developer',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi fuga alias quidem temporibus, sed, illum molestiae nostrum, in accusamus unde repellendus perspiciatis. Voluptate ducimus sunt nam laudantium id cum inventore!',
    date: '2023-01-25',
    type: 'contract',
    location: 'USA only',
    isFeatured: false,
    tags: ['frontend', 'junior', 'css', 'javascript'],
  },
  {
    id: 12,
    company: 'Manage',
    position: 'fullstack developer',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi fuga alias quidem temporibus, sed, illum molestiae nostrum, in accusamus unde repellendus perspiciatis. Voluptate ducimus sunt nam laudantium id cum inventore!',
    date: '2023-01-20',
    type: 'part time',
    location: 'remote',
    isFeatured: false,
    tags: ['fullstack', 'middle', 'python', 'react'],
  },
  {
    id: 13,
    company: 'Loop Studios',
    position: 'software engineer',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi fuga alias quidem temporibus, sed, illum molestiae nostrum, in accusamus unde repellendus perspiciatis. Voluptate ducimus sunt nam laudantium id cum inventore!',
    date: '2023-01-17',
    type: 'full time',
    location: 'worldwide',
    isFeatured: false,
    tags: ['fullstack', 'middle', 'sass', 'javascript', 'ruby'],
  },
  {
    id: 14,
    company: 'FaceIt',
    position: 'backend developer',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi fuga alias quidem temporibus, sed, illum molestiae nostrum, in accusamus unde repellendus perspiciatis. Voluptate ducimus sunt nam laudantium id cum inventore!',
    date: '2023-01-06',
    type: 'full time',
    location: 'UK only',
    isFeatured: false,
    tags: ['backend', 'junior', 'ruby', 'ror'],
  },
];
